#Task 1 Create Tables Based on ERD

create table customer (
    Customer_id int ,
    First_name varchar(50),
    Last_name varchar(50),
    Email varchar(50),
    Email_website varchar(50),
    Phone varchar(50),
    Street varchar(50),
    City varchar(50),
    State varchar(50),
    Zip_code varchar(50)
);

#task 2 Import CSVs into SQL using import wizard

create database retail;
use retail;
select * from brands;
select * from categories;
select * from customers;
select * from order_items;
select * from orders;
select * from products;
select * from staffs;
select * from stocks;
select * from stores;

#task 3 Join orders, order_items, and products to display detailed line items.

select orders.order_id,orders.customer_id,products.product_id,products.product_name,
order_items.Quantity,order_items.list_price,order_items.discount1 from orders join order_items on 
orders.order_id= order_items.order_id join products on order_items.product_id= products.product_id
order by orders.order_id,products.product_name;

#task 4 Write a query to group sales (total_price) by each store_id.

select orders.store_id,stores.store_name,sum(order_items.quantity*order_items.list_price*(1-order_items.discount1)) as Total_sales from orders 
join order_items on orders.order_id=order_items.order_id 
join stores on orders.store_id=stores.store_id
group by orders.store_id,stores.store_name;

#task 5 Use ORDER BY and LIMIT to get the top 5 most sold products by quantity

select product_id,product_name,sum(quantity)as Total_qty from order_items group by product_id,product_name order by Total_qty desc limit 5;

#task 6 For each customer, return total orders placed, total items purchased, and total revenue.

select customers.customer_id,customers.first_name as customer_name, count( distinct orders.order_id) as total_order,
sum(order_items.quantity) as Total_Qty, 
sum(order_items.quantity*order_items.list_price*(1-order_items.discount1)) as Total_sale from customers 
join orders on customers.customer_id=orders.customer_id 
join order_items on orders.order_id=order_items.order_id group by customers.customer_id,first_name
order by total_sale desc;

#task 7 Write a query to classify customers into spending brackets (e.g., low, medium, high).

select customers.customer_id,customers.first_name as customer_name, count( distinct orders.order_id) as total_order,
sum(order_items.quantity*order_items.list_price*(1-order_items.discount1)) as total_spent,
case
when sum(order_items.quantity*order_items.list_price*(1-order_items.discount1))<5000 
then 'Low' when sum(order_items.quantity*order_items.list_price*(1-order_items.discount1)) between 5000 and 15000 
then 'mid' else 'high' end as spending_brackets from customers 
join orders on customers.customer_id=orders.customer_id
join order_items on orders.order_id=order_items.order_id
group by customer_id,first_name order by total_spent desc;

# task 8 Analyze total revenue generated by each staff member based on their handled orders.

select orders.store_id,orders.staff_id,staffs.first_name as staff_name,sum(order_items.quantity*order_items.list_price*(1-order_items.discount1)) as sales
from orders join order_items on orders.order_id=order_items.order_id
join staffs on orders.staff_id=staffs.staff_id
group by orders.staff_id,orders.store_id order by staff_id;

#task 9 Write a query to list products where stock quantity < 10 in any store

select stocks.store_id,stocks.product_id,products.product_name,stocks.quantity from stocks
join products on products.product_id=stocks.product_id
where stocks.quantity<10 order by stocks.store_id;

#task 10 Create a table customer_segments that will be populated from Python ML results later.

create table customer_segments (
 customer_id int,
 customer_name varchar(50),
 recency int,
 frequency int,
 monetary double
 );

select * from customer_segments;








